### ISSUE TITLE
Problem with resources folder

### ISSUE THREAD

**Issue by lalil0u** [CellCognition/cecog#194]
Hi,

When installing current CellCognition master version in the relevant place, by doing python setup.py build, python setup.py install, the following problem arises: the folder resources is not copied to [correct directory]/lib/python2.7/site-packages. Hence I get the following error:
IOError: Resource path '[correct directory]/lib/python2.7/site-packages/resources' not found.

A manual copy solves the problem perfectly, however I think that this is a bug easily fixed.

Thanks!
Alice

**Comment by rhoef** [comment]
HI, 
on Linux it gets copied to /usr/share/.... The exception is related to a changed in the find_resource_folder function. 
Thomas fixed this recently.
