### ISSUE TITLE
Installation failed on linux ubuntu 14.04

### ISSUE THREAD

**Issue by cedunia** [CellCognition/cecog#199]
i follow the instruction to install cecogAnalyzer but i've got this error 
Traceback (most recent call last):
  File "/usr/local/bin/CecogAnalyzer.py", line 49, in <module>
    from cecog.gui.main import CecogAnalyzer
  File "/usr/local/lib/python2.7/dist-packages/cecog/gui/main.py", line 49, in <module>
    from cecog.gui.analyzer.general import GeneralFrame
  File "/usr/local/lib/python2.7/dist-packages/cecog/gui/analyzer/__init__.py", line 50, in <module>
    from cecog.analyzer.core import AnalyzerCore
  File "/usr/local/lib/python2.7/dist-packages/cecog/analyzer/core.py", line 23, in <module>
    from cecog.analyzer.position import PositionAnalyzer, PositionAnalyzerForBrowser
  File "/usr/local/lib/python2.7/dist-packages/cecog/analyzer/position.py", line 27, in <module>
    from cecog.analyzer.timeholder import TimeHolder
  File "/usr/local/lib/python2.7/dist-packages/cecog/analyzer/timeholder.py", line 35, in <module>
    from cellh5 import CH5Const, CH5File, CH5Position
ImportError: No module named cellh5
Anyone can help me ?

Thanks.

**Comment by rhoef** [comment]
Hi,

you need to install the cellh5 package.
https://github.com/CellH5/cellh5

best regards


Am 24/04/15 um 17:30 schrieb cedunia:

**Comment by cedunia** [comment]
Thanks for your answer but i've got a new error ! ImportError: libvigraimpex.so.6: cannot open shared object file: No such file or directory. This lib is found on /usr/local/lib directory.

Thanks for your help

**Comment by sommerc** [comment]
seems like, libvigraimpex is missing a dependency. Can you do an ldd on libvigraimpex?

**Comment by cedunia** [comment]
result of ldd libvigraimpex.so.6
linux-vdso.so.1 =>  (0x00007fff7cbfe000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f7e19eb2000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f7e19c8c000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f7e19a72000)
	libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007f7e19800000)
	libhdf5.so.7 => /usr/lib/x86_64-linux-gnu/libhdf5.so.7 (0x00007f7e19364000)
	libhdf5_hl.so.7 => /usr/lib/x86_64-linux-gnu/libhdf5_hl.so.7 (0x00007f7e19133000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7e18e2f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7e18b29000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7e18912000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7e186f4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7e1832f000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f7e1810c000)
	libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007f7e17efe000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7e17cfa000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7e1a3a4000)

**Comment by rhoef** [comment]
Hi,

the problem is that your location where libvigra is installed is not set 
to the LD_LIBRARY_PATH

heres a link how to setup this. Ubuntu unfortunately missed this 
directory in their setup.

http://stackoverflow.com/questions/13428910/how-to-set-the-environmental-variable-ld-library-path-in-linux


Am 27/04/15 um 14:03 schrieb cedunia:

**Comment by cedunia** [comment]
After set LD_LIBRARY_PATH and install rdflib and ontospy modules missing; it's works.
Thanks very much !
