### ISSUE TITLE
ImportError: cannot import name Ontology

### ISSUE THREAD

**Issue by drmatthews** [CellCognition/cecog#207]
Hi

I am trying to install cecog on Ubuntu 15.04. I installed all the dependencies listed in the wiki but then got a module import error for ontospy. I installed ontospy 1.6.2 using pip but now I get an import error for the Ontology class. When I looked at the source code for ontospy there doesn't seem to be an Ontology class in ontospy.ontospy. I must of missed something or have I installed the wrong package? If so what do I need to install?

This looks like a really interesting project so thanks for contributing it to the microscopy community!

Dan.

**Comment by xiwei-zhang** [comment]
Hi Dan,

I had the same problem recently. The easiest solution is to downgrade your
ontospy module to a version 1.2.x. I hope this function will be fixed in
the next release.

Regards,

Xiwei

2015-10-15 10:57 GMT+02:00 Daniel Matthews <notifications@github.com>:

**Comment by sommerc** [comment]
yes, the ontospy package completely changed it structure. Downgrading to 1.2 will help

**Comment by drmatthews** [comment]
worked - thank you very much!
