### ISSUE TITLE
Invalide 'pyrcc' command

### ISSUE THREAD

**Issue by PeterJackNaylor** [CellCognition/cecog#208]
Hi,

I was trying to install CellCognition on my windows 10 machine and I encountered an issue in the last bit. 
When I was trying to build the CellCognition resource file I get the following error when I type this command: 
C:\cellcognition>python setup_windows.py pyrcc --help
usage: setup_windows.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup_windows.py --help [cmd1 cmd2 ...]
   or: setup_windows.py --help-commands
   or: setup_windows.py cmd --help

error: invalid command 'pyrcc'

At first, after looking at the python_windows.py script I thought it was an issue with pyqt5 and especially with the missing pyrcc5 file, but after reinstalling it via git like it was suggested to me. These commands still fail. Would anyone have an idea? 
Thanks

**Comment by sommerc** [comment]
Hey Peter, 

did you try the command:

python setup_windows.py build_rcc 

Cheers,
Chris

**Comment by PeterJackNaylor** [comment]
Hi Chris,

No I had not tried that command. The command worked without any problem, but I still get the same error message as described in my first post.
Thanks,

Peter

**Comment by sommerc** [comment]
can you check if you have to file:

c:\Python27\Lib\site-packages\PyQt5\pyrcc5.exe

PS: I assume you followed the instructions on, right?
https://github.com/CellCognition/cecog/wiki/Windows-x64-(MSVS-2013)-source-installation-guide

Cheers, Chris

**Comment by PeterJackNaylor** [comment]
Hi,

Yes I checked as I thought it was the issue at first. ( https://github.com/pyqt/python-qt5/issues/12 )
So yes I have it, I also changed lines 39/40 of setup_windows.py script so that it would go to my pyrcc5.exe file, which was in my Anaconda distribution files.

Cheers,
Peter

**Comment by sommerc** [comment]
hmm, what's the exact error when you execute

python setup_windows.py build_rcc

or 

python setup_windows.py build_help

?

**Comment by PeterJackNaylor** [comment]
There are no errors.

**Comment by sommerc** [comment]
ok, and does it work then?

**Comment by PeterJackNaylor** [comment]
the command python setup_windows.py pyrcc still doesn't work. (pyrrc command not found)

So I tried just ignoring it and running python CecogAnalyser.py, and notice I have a cellh5 depencies missing.

**Comment by PeterJackNaylor** [comment]
Ok, I succed in installing all the different dependencies.
I had to install the packages cellh5 (from github) and then adding it to the PYTHONPATH.
I installed rdflib also and the version 1.2.3 of ontospy. (Couldn't take a later version as the object Ontology doesn't exist).

I still have an issue that is: 
So this issue arrise when I try:
python CecogAnalyser.py 

C:\cellcognition\scripts>python CecogAnalyzer.py
Traceback (most recent call last):
  File "CecogAnalyzer.py", line 109, in <module>
    args.configfile, args.debug)
  File "..\cecog\gui\main.py", line 129, in __init__
    debug=debug)
  File "..\cecog\util\pattern.py", line 33, in __call__
    cls._instances[pid] = super(Singleton, cls).__call__(*args, **kwargs)
  File "..\cecog\environment.py", line 139, in __init__
    self._copy_config(self)
  File "..\cecog\environment.py", line 165, in _copy_config
    os.mkdir(self.user_config_dir)
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Users\\Peter\\Application Data\\CellCognition1.6.0'


And so, yes I don't have an Application Data Folder there... But I don't really know what to do from here.

Any thoughts?
Cheers,
Peter

**Comment by rhoef** [comment]
Hi,
build_rcc is just the new name of pyrcc (most commands are called "build_xxx"). 

It is essential that the directory  'C:\Users\Peter\Application Data\" exists (no Cellcognition1.6 at the end). Some data and settings is stored the. Either, assuming you have the permissions, you make the directory or you change the source code (function "user_config_dir" in file environment.py). I recommend the first solution:)

Check if the Directory exisists. If you start Cellcognition unsuccessfully its better to delete it to have a virgin environment.

-- Rudi

**Comment by PeterJackNaylor** [comment]
Ok, thanks for the reply. 
All working good! I just had to create the directory.
Thanks.

Peter
