### ISSUE TITLE
stability problem in the master

### ISSUE THREAD

**Issue by ThomasWalter** [CellCognition/cecog#209]
Hey, 

I tried to run the current version from the master branch (I am currently writing the help files for the segmentation plugins).

There seem to be a few issues. I fixed the first related to the settings filename which caused the program to abort, but here is another one. When I click on the labels in the GUI (such as "Skip finished positions" or "Timelapse" in the part "General") the program aborts with the error message: 

Traceback (most recent call last):
  File "/Users/twalter/cecog_install/lib/python2.7/site-packages/cecog/gui/display.py", line 477, in mouseReleaseEvent
    if link is not None:
NameError: global name 'link' is not defined

**Comment by rhoef** [comment]
Hi, 
in line 477 simply write "self.link" instead of "link". I thought I fixed this bug already, obviously not:)
