### ISSUE TITLE
RuntimeError: file submodules/css/pyqtcss/src/classic/style.qrc not found

### ISSUE THREAD

**Issue by lalil0u** [CellCognition/cecog#219]
Hi,

When installing CellCognition on Ubuntu, `git submodule update` fails because the initial datasets are not available yet. Therefore, I think that what happens is that the css files for qt are not downloaded either, and when running `python setup.py build`, it gives the above RuntimeError. My workaround was to clone https://github.com/sommerc/pyqt-stylesheets.git and put its content in the right folder for the setup.py to find it.

Alice

**Comment by lalil0u** [comment]
Hi Rudi,

I had indeed done git submodule init. Here is the full log:
```
..:~/tttt$ cd cecog
..:~/tttt/cecog$ git submodule init
Submodule 'resources/battery_package' (git@github.com:CellCognition/battery_package.git) registered for path 'resources/battery_package'
Submodule 'submodules/css' (https://github.com/sommerc/pyqt-stylesheets.git) registered for path 'submodules/css'
..:~/tttt/cecog$ git submodule update
Cloning into 'resources/battery_package'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:CellCognition/battery_package.git' into submodule path 'resources/battery_package' failed
..:~/tttt/cecog$ python setup.py build
running build
running build_rcc
Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    **build_helpers.metadata)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
```

**Comment by rhoef** [comment]
Hi, 
according to the log it fails already when cloning the battery_package. Please check if all files of the battery_package are there. If not it could be an outdated Public Access key to github

**Comment by lalil0u** [comment]
Modifying the .gitmodules as you suggest it works. It gives the log:

> [..]:~/tttt/cecog$ git submodule update
> Cloning into 'resources/battery_package'...
> remote: Counting objects: 18729, done.
> remote: Total 18729 (delta 0), reused 0 (delta 0), pack-reused 18729
> Receiving objects: 100% (18729/18729), 14.79 MiB | 3.95 MiB/s, done.
> Resolving deltas: 100% (10646/10646), done.
> Checking connectivity... done.
> fatal: reference is not a tree: feb2fd4f0de920ecde182a27f687c3ae9832222d
> Cloning into 'submodules/css'...
> remote: Counting objects: 141, done.
> remote: Compressing objects: 100% (103/103), done.
> remote: Total 141 (delta 34), reused 141 (delta 34), pack-reused 0
> Receiving objects: 100% (141/141), 57.63 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (34/34), done.
> Checking connectivity... done.
> Submodule path 'submodules/css': checked out '7b4462d5588834c198b2fa8369bd1e52ce2cad14'
> Unable to checkout 'feb2fd4f0de920ecde182a27f687c3ae9832222d' in submodule path 'resources/battery_package'
> 
Nevertheless, the folder resources/battery_package is still empty, although the css one is not.

I did not specify any branch so I guess it is the master one. But I still have the other error.

**Comment by rhoef** [comment]
Hi, 
I changed the link to the https version of the battery_package so that no password is required when the battery package is cloned. 

You probably need to setup a new SSH key on github in order clone a repo the uses the link that starts with "git" instead of "https"

-- R

**Comment by lalil0u** [comment]
OK, thanks!
