### ISSUE TITLE
Installation on Ubuntu16.04 not building

### ISSUE THREAD

**Issue by lalil0u** [CellCognition/cecog#220]
Hi,

When installing on Ubuntu16.04, and running `python setup.py build`, I get the following error:

> running build_ext
> building 'cecog.ccore._cecog' extension
> C compiler: x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC
> 
> creating build/temp.linux-x86_64-2.7
> creating build/temp.linux-x86_64-2.7/csrc
> creating build/temp.linux-x86_64-2.7/csrc/src
> compile options: '-Icsrc/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c'
> extra options: '-O3 -fPIC'
> Warning: Can't read registry to find the necessary compiler setting
> Make sure that Python modules _winreg, win32api or win32con are installed.
> x86_64-linux-gnu-gcc: csrc/src/cecog.cxx
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
>                  from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
>                  from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
>                  from csrc/include/cecog/wrapper/wrap_images.hxx:37,
>                  from csrc/src/cecog.cxx:27:
> 
> [...]
> 
> error: Command "x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Icsrc/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c csrc/src/cecog.cxx -o build/temp.linux-x86_64-2.7/csrc/src/cecog.o -O3 -fPIC" failed with exit status 1

I do have installed python2.7-dev... I cannot see from Google where the error comes from. Thanks!!
Alice

**Comment by rhoef** [comment]
Hi, 
I'm not entirely sure but did you edit the setup.cfg file (there is a template setup.cfg.in) to tell where the boost and vigra libraries are installed.

-- R

**Comment by lalil0u** [comment]
Hi Rudi,

Thank you for your help. Here is my setup.cfg content:
```
[build_ext]
include_dirs=/usr/local/include:/usr/include:/usr/local/include/vigra
library_dirs=/usr/local/lib:/usr/lib:/usr/lib/x86_64-linux-gnu

# vigra 1.10, boost 1.57
include_dirs=/usr/local/include:/usr/include:/usr/local/include/vigra
library_dirs=/usr/local/lib:/usr/lib:/usr/lib/x86_64-linux-gnu
```
In /usr/include there is the boost folder and in /usr/local/include the vigra folder, and in /usr/local/lib there is the libvigraimpex.so and a vigra folder. In /usr/lib/x86_64-linux-gnu/ there are the libboost*.so. I attach a file with all the steps I did up to this one, to install CellCognition.

Thank you for your help!
Alice
[Installing_Cecog.txt](https://github.com/CellCognition/cecog/files/487916/Installing_Cecog.txt)

**Comment by rhoef** [comment]
According to the "Installing_Cecog.txt" you compiled some library by your self. Please try the description in the [wiki](https://github.com/CellCognition/cecog/wiki/Linux-install-guide-for-1.6.x-with-PyQt5-%28Debian-based%29). Prefer the packages from the ubuntu repo if possible. Even an current libvigra should be available.

**Comment by lalil0u** [comment]
I did try to follow the wiki as much as possible, but it was not always working. For example, `sudo apt-get install python-qt5` gives `E: Unable to locate package python-qt5`. Same for python-qt5-dev.

**Comment by rhoef** [comment]
Sorry the packages have different names ```python-pyqt5, pyqt5``` etc. make sure you install ```pyqt5-dev-tools```. Check if you find the commands ```pyrcc5```and ```qcollectiongenerator```. Please check the names on Ubuntu, I use Debian.

To install libsvm use the command ```python setup.py install``` in order to place the files including the shared libraries in the correct places. No need to copy the files manually.  Make sure to change to the directory ```libsvm-2.89/python``` (old python binding). 

-- R

**Comment by lalil0u** [comment]
Hi Rudi,
So 
- `python setup.py build` or `python setup.py install` raises an error (see underneath), but I have installed libsvm-3.21 and I can do `from svmutil import *` in the ipython shell,
- I can find both pyrcc5 and qcollection generator commands.

Alice

> asebag@Rastignac:~/software/Installed/libsvm-2.89/python$ python setup.py build
> running build
> running build_py
> running build_ext
> building 'svmc' extension
> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c ../svm.cpp -o build/temp.linux-x86_64-2.7/../svm.o -O3 -I../
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> ../svm.cpp: In function ‘svm_model* svm_load_model(const char*)’:
> ../svm.cpp:2738:24: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
>    fscanf(fp,"%80s",cmd);
>                         ^
> ../svm.cpp:2742:25: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
>     fscanf(fp,"%80s",cmd);
>                          ^
> ../svm.cpp:2764:25: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
>     fscanf(fp,"%80s",cmd);
>                          ^
> ../svm.cpp:2785:33: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
>     fscanf(fp,"%d",&param.degree);
>                                  ^
> ../svm.cpp:2787:33: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
>     fscanf(fp,"%lf",&param.gamma);
>                                  ^
> ../svm.cpp:2789:33: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
>     fscanf(fp,"%lf",&param.coef0);
>                                  ^
> ../svm.cpp:2791:36: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
>     fscanf(fp,"%d",&model->nr_class);
>                                     ^
> ../svm.cpp:2793:29: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
>     fscanf(fp,"%d",&model->l);
>                              ^
> ../svm.cpp:2799:36: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
>      fscanf(fp,"%lf",&model->rho[i]);
>                                     ^
> ../svm.cpp:2806:37: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
>      fscanf(fp,"%d",&model->label[i]);
>                                      ^
> ../svm.cpp:2813:38: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
>      fscanf(fp,"%lf",&model->probA[i]);
>                                       ^
> ../svm.cpp:2820:38: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
>      fscanf(fp,"%lf",&model->probB[i]);
>                                       ^
> ../svm.cpp:2827:35: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
>      fscanf(fp,"%d",&model->nSV[i]);
>                                    ^
> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c svmc_wrap.c -o build/temp.linux-x86_64-2.7/svmc_wrap.o -O3 -I../
> svmc_wrap.c: In function ‘SWIG_Python_AddErrorMsg’:
> svmc_wrap.c:853:5: error: format not a string literal and no format arguments [-Werror=format-security]
>      PyErr_Format(PyExc_RuntimeError, mesg);
>      ^
> cc1: some warnings being treated as errors
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by rhoef** [comment]
Hi,
you need to link the python bindings against the same version of libsvm. 
[Here](https://drive.google.com/drive/folders/0B-gU9FiZA8ITREhFUXJhUXZaOGs?usp=sharing) is a link with recompiled Debain packages. Be aware that I have compiled them on Debian Jessie not Ubuntu so it might not work, but I may help you save time. Install all the *.deb files.

- R

**Comment by lalil0u** [comment]
Hi Rudi,

Thanks for your help, I've deleted all previous libsvm installation and installed it from the *.deb files (4 deb files in the folder you shared). However I still get the same errors. I've checked that the libsvm files are in /usr/lib and /usr/include which are in the cecog config file.

Alice

**Comment by lalil0u** [comment]
An update: after some Googling I've found out that this type of error can come from a bad python installation. So I removed all python3* folders from the paths used in the config file. And now I get the following error:

> Compiling qrc submodules/css/pyqtcss/src/classic/style.qrc
> cecog/css/classic_rc.py
> Could not find platform independent libraries <prefix>
> Could not find platform dependent libraries <exec_prefix>
> Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
> Fatal Python error: Py_Initialize: Unable to get the locale encoding
>   File "/usr/lib/python2.7/encodings/__init__.py", line 123
>     raise CodecRegistryError,\
>                             ^
> SyntaxError: invalid syntax
> 
> Current thread 0x00007f5e74daf700 (most recent call first):
> running command 'pyrcc5 -o cecog/css/classic_rc.py submodules/css/pyqtcss/src/classic/style.qrc' failed
> Traceback (most recent call last):
>   File "setup.py", line 64, in <module>
>     **build_helpers.metadata)
>   File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
>     dist.run_commands()
>   File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
>     cmd_obj.run()
>   File "/home/asebag/software/Installed/cecog/build_helpers/commands.py", line 30, in run
>     self.run_command('build_rcc')
>   File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
>     cmd_obj.run()
>   File "/home/asebag/software/Installed/cecog/build_helpers/commands.py", line 97, in run
>     subprocess.check_call([self.pyrccbin, '-o', outfile, infile])
>   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['pyrcc5', '-o', 'cecog/css/classic_rc.py', 'submodules/css/pyqtcss/src/classic/style.qrc']' returned non-zero exit status -6
So it seems that there was some mixup between python2.7 and 3 in my installation of something.

**Comment by lalil0u** [comment]
After some Googling I think I've identified that this comes from PyQt5 being installed for python3.5. On PyQt5 they say that if one does `pip3 install pyqt5` it will by default know which python to bind against, but here I've even used virtualenv to test different Python environments, and my PyQt5 is in the end always in a python3.5 folder. So I guess the question is, do you know how I could install PyQt5 for Python2.7?

**Comment by rhoef** [comment]
Hi, 
always use the packages from the distribution first. Ubunutu for sure hast pyqt5 for python2.7 included.

-- R

**Comment by lalil0u** [comment]
Hi Rudi,

I'm not so sure about that. On the PyQt5 website it says: 
> Wheels are the standard Python packaging format for pure Python or binary extension modules such as PyQt5. PyQt5 wheels are specific to a particular version of Python. **Only Python v3.5 and later is supported.**

All I could find on my computer related to PyQt5 was in python3.5 dist-package folders (Ubuntu 16.04, maybe this is new). So this morning I reinstalled all PyQt5-related code, making sure I'm using python2 configure.py, and I still get the same error. Please let me know if you see how to fix this, otherwise let's forget it.

**Comment by rhoef** [comment]
Hi, 
as far is I found it quickly those packages exist. [look here](https://launchpad.net/ubuntu/xenial/+source/pyqt5)
 May be the repository is not enabled. Anyway if it's easier to compile the bindings your self but I still recommend to use packages from official repositories. 

-- R

**Comment by stelfrich** [comment]
This issue still remains (maybe for different reasons than before):

The Ubuntu package `python-sklearn` provides scikit-learn 0.17.x which does [no longer contain](http://scikit-learn.sourceforge.net/stable/modules/hmm.html) the `hmm` module. I have tried to replace the imports in Cecog with new ones to `hmmlearn` as per suggestion: the new `hmm` module does not provide `decoder_algorithms` :-1: 

Any idea, @rhoef?

**Comment by rhoef** [comment]
Sorry for the inconvenience but for the moment you have to stick with sklearn 0.16. 

-- rhoef

PS
To avoid version clashes you could try an older version of hmmlearn (since you have already replaced the imports) but this is at you own risk.
