### ISSUE TITLE
Cannot be started

### ISSUE THREAD

**Issue by GRDias** [CellCognition/cecog#224]
I can't start the software. 
Log file:
_Traceback (most recent call last):
  File "CecogAnalyzer.py", line 42, in <module>
  File "PyQt5\QtGui.pyo", line 12, in <module>
  File "PyQt5\QtGui.pyo", line 10, in __load
ImportError: DLL load failed: The specified procedure could not be found._
Can you guys help me?

**Comment by rhoef** [comment]
This is because Cell Cognition does not support Windows10 yet. The Binaries are only for Windows 7&8. 
Sorry

**Comment by cgohlke** [comment]
FWIW, `CecogAnalyzer_1.6.1_x86_64.exe` bundles some Windows system files that seem to conflict with Windows 10. At least on this Windows 10 1909 system, CecogAnalyzer 1.6.1 starts after deleting the following files from the CecogAnalyzer installation directory:
```
API-MS-Win-Security-Base-L1-1-0.dll
API-MS-Win-Security-SDDL-L1-1-0.dll
CRYPT32.dll
d3d8thk.dll
d3d9.dll
dwmapi.dll
```
