### ISSUE TITLE
Having problems with Error Correction

### ISSUE THREAD

**Issue by pramal1997** [CellCognition/cecog#226]
When I try to run my data with CellCognition, I encounter this error while trying to do error correction (after performing object detection, classification, tracking and event selection in sequential order). I encounter the same problem when trying to run the data provided by CellCognition website. I am using Windows 7 & and CellCog 1.6.1 (latest version). Do I have to insert any files or something for this to work?

![error correction](https://user-images.githubusercontent.com/39563377/40435974-1f6c25d8-5e6f-11e8-84dc-ec2d24652d1e.PNG)

**Comment by sommerc** [comment]
Have events been found? Are you using cellh5 in output?
